model_name: t5
run_dir: /path/to/directory/where/everything/will/be/saved
model_config: /path/to/model/configs/model-configs/t5/bevt-efficient-large.json
model_checkpoint: GermanT5/t5-efficient-gc4-all-german-large-nl36
tokenizer_checkpoint: GermanT5/t5-efficient-gc4-all-german-large-nl36
processor_checkpoint: GermanT5/t5-efficient-gc4-all-german-large-nl36
target_language: German
train_files: /path/to/data/wmt23/info/train.tsv
train_labels: /path/to/data/wmt23/info/train.wrd
valid_files: /path/to/data/wmt23/info/valid.tsv
valid_labels: /path/to/data/wmt23/info/valid.wrd
features_dir: /path/to/video/representations/BEVT-OASLWLASL-LAYER24
expand_time: false
freeze_model: false
freeze_adapter: false
force_target_language: false
batch_size_per_gpu: 8
accumulation_steps: 1
learning_rate: 0.001
warmup_steps: 0
train_steps: 8001
fp16: false
test_every: 500
save_every: 500
log_every: 500
num_workers: 0
auto_resume: true
optimizer: adafactor
schedule: linear
weight_decay: 0.0
