model_name: whisper
run_dir: /directory/where/everything/will/be/saved
model_config: /path/to/directory/containing/model-configs/whisper/bevt-tiny.json
model_checkpoint: openai/whisper-tiny
processor_checkpoint: openai/whisper-tiny
target_language: German
train_files: /path/to/data/wmt23/info/train.tsv
train_labels: /path/to/data/wmt23/info/train.wrd
valid_files: /path/to/data/wmt23/info/valid.tsv
valid_labels: /path/to/data/wmt23/info/valid.wrd
features_dir: /path/to/extracted/video/representations/BEVT-OASLWLASL-LAYER24
expand_time: true
freeze_model: false
freeze_adapter: false
force_target_language: true
batch_size_per_gpu: 8
accumulation_steps: 1
learning_rate: 0.001
warmup_steps: 100
train_steps: 11000
fp16: true
test_every: 100
save_every: 100
log_every: 10
num_workers: 0
auto_resume: true
weight_decay: 0.0
schedule: cosine
optimizer: adamw_torch

